In [1]:
import ALS

In [2]:
df = ALS.get_dataframes(2, 0.5)

227 movies left in data
['movieId', 'rating', 'userId']
['userId', 'movieId', 'rating']


In [3]:
df[1]

array([[0,
        list([0, 1, 2, 3, 4, 5, 6, 7, 8, 9, 10, 11, 12, 13, 14, 15, 16, 17, 18, 19, 20, 21, 22, 23, 24, 25, 26, 27, 28, 29, 30, 31, 32, 33, 34, 35, 36, 37, 38, 39, 40, 41, 42, 43, 44, 45, 46, 47, 48, 49, 50, 51, 52, 53, 54, 55, 56, 57, 58, 59, 60, 61, 62, 63, 64, 65, 66, 67, 68, 69, 70, 71, 72, 73, 74, 75, 76, 77, 78, 79, 80, 81, 82, 83, 84, 85, 86, 87, 88, 89, 90, 91, 92, 93, 94, 95, 96, 97, 98, 99, 100, 101, 102, 103, 104, 105, 106, 107, 108, 109, 110, 111, 112, 113, 114, 115, 116, 117, 118, 119, 120, 121, 122, 123, 124, 125, 126, 127, 128, 129, 130, 131, 132, 133, 134, 135, 136, 137, 138, 139, 140, 141, 142, 143, 144, 145, 146, 147, 148, 149, 150, 151, 152, 153, 154, 155, 156, 157, 158, 159, 160, 161, 162, 163, 164, 165, 166, 167, 168, 169, 170, 171, 172, 173, 174]),
        list([0.7, 0.8, 0.7, 0.7, 0.6, 0.7, 0.7, 0.8, 1.0, 0.7, 0.7, 0.8, 0.7, 0.7, 0.7, 0.7, 0.8, 0.8, 0.7, 0.7, 0.8, 0.8, 0.7, 0.8, 0.7, 0.7, 0.8, 0.7, 0.8, 0.6, 0.7, 0.8, 0.8, 0.7, 0.8, 0.8, 0.8, 0.7, 1.0,

In [4]:
df[2]

array([[0, list([0.7]), list([0])],
       [1, list([0.8]), list([0])],
       [2, list([0.7]), list([0])],
       [3, list([0.7]), list([0])],
       [4, list([0.6]), list([0])],
       [5, list([0.7]), list([0])],
       [6, list([0.7]), list([0])],
       [7, list([0.8]), list([0])],
       [8, list([1.0]), list([0])],
       [9, list([0.7]), list([0])],
       [10, list([0.7]), list([0])],
       [11, list([0.8, 1.0]), list([0, 1])],
       [12, list([0.7]), list([0])],
       [13, list([0.7]), list([0])],
       [14, list([0.7]), list([0])],
       [15, list([0.7]), list([0])],
       [16, list([0.8]), list([0])],
       [17, list([0.8]), list([0])],
       [18, list([0.7]), list([0])],
       [19, list([0.7]), list([0])],
       [20, list([0.8]), list([0])],
       [21, list([0.8]), list([0])],
       [22, list([0.7]), list([0])],
       [23, list([0.8]), list([0])],
       [24, list([0.7]), list([0])],
       [25, list([0.7]), list([0])],
       [26, list([0.8]), list([0])],
   

In [19]:
df[0][:, 1]

array([  1.,   2.,   4.,   6.,   7.,  11.,  11.,  13.,  14.,  20.,  22.,
        23.,  24.,  25.,  26.,  27.,  30.,  36.,  37.,  38.,  42.,  43.,
        44.,  47.,  50.,  52.,  54.,  57.,  58.,  60.,  61.,  62.,  64.,
        65.,  66.,  68.,  69.,  70.,  70.,  71.,  73.,  76.,  77.,  78.,
        79.,  81.,  82.,  85.,  86.,  88.,  90.,  92.,  93.,  95.,  97.,
        97.,  98.,  99., 102., 106., 107., 108., 110., 114., 116., 117.,
       119., 120., 121., 123., 125., 127., 129., 132., 139., 144., 146.,
       148., 149., 149., 150., 151., 153., 156., 157., 158., 160., 162.,
       163., 165., 166., 168., 169., 170., 172., 175., 180., 182., 183.,
       188., 194., 195., 196., 197., 198., 199., 202., 204., 207., 209.,
       211., 213., 216., 217., 222., 223., 224., 226.])

In [18]:
x

In [1]:
import ALS

In [15]:
ALS.main(30000, 0.05)

16496 movies left in data
['movieId', 'rating', 'userId']
['userId', 'movieId', 'rating']
nU: 30000
nP: 16496
loss_0: 3.738884449005127
ep: 0
after updating P loss: 0.5905869007110596
after updating U loss: 0.5430188775062561
this epoch took 46.17958092689514
ep: 1
after updating P loss: 0.5372327566146851
after updating U loss: 0.5380905866622925
this epoch took 44.18279767036438
ep: 2
after updating P loss: 0.5370883941650391
after updating U loss: 0.5377834439277649
this epoch took 44.98357582092285
ep: 3
after updating P loss: 0.5368666648864746
after updating U loss: 0.5385326743125916
this epoch took 44.69076895713806
ep: 4
after updating P loss: 0.5365238189697266
after updating U loss: 0.5388586521148682
this epoch took 44.4008207321167
ep: 5
after updating P loss: 0.5365359783172607
after updating U loss: 0.5386826395988464
this epoch took 44.23087120056152
ep: 6
after updating P loss: 0.5368951559066772
after updating U loss: 0.5380990505218506
this epoch took 44.737838268280

In [5]:
import torch
from sklearn.linear_model import LinearRegression

In [ ]:
def update_P(model, per_movieId_umr):
    for movie, ratings, users in per_movieId_umr:
        indices = torch.LongTensor(users)
        ratings_for_indices = torch.Tensor(ratings)
        U_tilde = model.U.index_select(0, indices)
        model.P[movie] = ratings_for_indices  @ U_tilde @ ((U_tilde.T @ U_tilde).inverse())

In [4]:
class Recommender(torch.nn.Module):

    def __init__(self, n_U, n_P, k):
        super(Recommender, self).__init__()

        self.U = torch.nn.Parameter(torch.rand(n_U, k, requires_grad=True))
        self.P = torch.nn.Parameter(torch.rand(n_P, k, requires_grad=True))

    def forward(self, i_user, i_product):
        i_user = int(i_user)
        i_product = int(i_product)
        user_vector = self.U[i_user]
        product_vector = self.P[i_product]
        return user_vector @ product_vector ## inner porduct

    def get_loss(self,umr):
        loss_fn = torch.nn.MSELoss()
        result = 0
        for u,m,r in umr:
            r_hat = self.forward(u, m)
            r = torch.Tensor([r]).squeeze()
            result += loss_fn(r_hat, r)
        return result / len(umr)

NameError: name 'torch' is not defined